// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {cluster} from '../models';

export function ClaimRecommendation(arg1:wails.RecommendationRequest):Promise<wails.OptimizationResult>;

export function DismissRecommendation(arg1:wails.RecommendationRequest):Promise<wails.OptimizationResult>;

export function GetClusterSnapshot(arg1:wails.ClusterSnapshotRequest):Promise<cluster.Snapshot>;

export function GetCostForecast(arg1:wails.CostForecastRequest):Promise<wails.CostForecastResult>;

export function GetCostReport(arg1:wails.CostReportRequest):Promise<wails.CostReportResult>;

export function GetCostTrend(arg1:wails.CostTrendRequest):Promise<wails.CostTrendResult>;

export function GetWorkloadYAML(arg1:wails.WorkloadYAMLRequest):Promise<string>;

export function ListEKSClusters(arg1:wails.EKSClustersRequest):Promise<Array<string>>;

export function ListKubeconfigContexts(arg1:wails.KubeconfigContextsRequest):Promise<Array<wails.KubeconfigContext>>;

export function MarkRecommendationApplied(arg1:wails.RecommendationRequest):Promise<wails.OptimizationResult>;

export function PrepareEKSConnection(arg1:wails.EKSConnectionRequest):Promise<wails.EKSConnectionResult>;

export function ReopenRecommendation(arg1:wails.RecommendationRequest):Promise<wails.OptimizationResult>;

export function RestoreRecommendation(arg1:wails.RecommendationRequest):Promise<wails.OptimizationResult>;

export function SetCostBudget(arg1:wails.CostBudgetRequest):Promise<void>;

export function SimulateManifest(arg1:wails.SimulationRequest):Promise<wails.SimulationResult>;

export function TestConnection(arg1:wails.ClusterConnectionRequest):Promise<wails.ClusterConnectionResult>;
