// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetClusterSnapshot(arg1) {
  return window['go']['wails']['ClusterAdapter']['GetClusterSnapshot'](arg1);
}

export function GetCostReport(arg1) {
  return window['go']['wails']['ClusterAdapter']['GetCostReport'](arg1);
}

export function GetCostTrend(arg1) {
  return window['go']['wails']['ClusterAdapter']['GetCostTrend'](arg1);
}

export function GetWorkloadYAML(arg1) {
  return window['go']['wails']['ClusterAdapter']['GetWorkloadYAML'](arg1);
}

export function ListEKSClusters(arg1) {
  return window['go']['wails']['ClusterAdapter']['ListEKSClusters'](arg1);
}

export function ListKubeconfigContexts(arg1) {
  return window['go']['wails']['ClusterAdapter']['ListKubeconfigContexts'](arg1);
}

export function PrepareEKSConnection(arg1) {
  return window['go']['wails']['ClusterAdapter']['PrepareEKSConnection'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['wails']['ClusterAdapter']['TestConnection'](arg1);
}
