// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListKubeconfigContexts(arg1) {
  return window['go']['wails']['ClusterAdapter']['ListKubeconfigContexts'](arg1);
}

export function TestConnection(arg1) {
  return window['go']['wails']['ClusterAdapter']['TestConnection'](arg1);
}
