// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';
import {cluster} from '../models';

export function GetClusterSnapshot(arg1:wails.ClusterSnapshotRequest):Promise<cluster.Snapshot>;

export function GetWorkloadYAML(arg1:wails.WorkloadYAMLRequest):Promise<string>;

export function ListEKSClusters(arg1:wails.EKSClustersRequest):Promise<Array<string>>;

export function ListKubeconfigContexts(arg1:wails.KubeconfigContextsRequest):Promise<Array<wails.KubeconfigContext>>;

export function PrepareEKSConnection(arg1:wails.EKSConnectionRequest):Promise<wails.EKSConnectionResult>;

export function TestConnection(arg1:wails.ClusterConnectionRequest):Promise<wails.ClusterConnectionResult>;
