// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EstimateManifest(arg1) {
  return window['go']['wails']['ManifestAdapter']['EstimateManifest'](arg1);
}
